import androidx.compose.ui.graphics.Color

val SpendLessBlack = Color(0xFF1B1B1C)
val SpendLessDarkGrey = Color(0xFF44474B)
val SpendLessPurple = Color(0xFF5A00C8)
val SpendLessWhite = Color(0xFFFFFFFF)
val SpendLessRed = Color(0xFFA40019)
val SpendLessPaleLavender = Color(0xFFFEF7FF)
val SpendLessLightGrey = Color(0xFF1D1A25)
val SpendLessPrimaryFixed = Color(0xFFEADDFF)
val SpendLessOnPrimaryFixed = Color(0xFF24005A)
val SpendLessSurfaceContainerLow = Color(0xFFF6F3F3)
val SpendLessSurfaceContainerLowest = Color(0xFFFFFFFF)
val SpendLessGreen = Color(0xFF29AC08)
val SpendLessPrimaryContainer = Color(0xFF8138FF)
val SpendLessOnPrimaryContainer = Color(0xFFFFFFFF)
val SpendLessInversePrimary = Color(0xFFD2BCFF)
val SpendLessSecondaryFixed = Color(0xFFE5EA58)
val SpendLessSecondaryContainer = Color(0xFFD2E750)
val SpendLessSecondaryFixedDim = Color(0xFFC9CE3E)
val SpendLessOnSecondaryContainer = Color(0xFF414300)
val SpendLessTertiaryContainer = Color(0xFFC4E0F9)
val SpendLessSecondary = Color(0xFF5F6200)
val SpendLessSuccess = Color(0xFF29AC08)
